apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb-coredns-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-pub
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.1
  ports:
  - port: 53
    protocol: TCP
    targetPort: 53

---

apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb-coredns-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-pub
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.1
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
