apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: emergy/hipster-frontend:v0.0.2
        env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "localhost:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "localhost:7000"
          - name: CART_SERVICE_ADDR
            value: "localhost:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "localhost:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "localhost:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "localhost:5050"
          - name: AD_SERVICE_ADDR
            value: "localhost:9555"
          - name: ENV_PLATFORM
            value: "test"


